Repository TestRigor/actions-recorder, pull requests merged in 2020-04, with the labels that each got.

#37 Fix object className for use tag inside svg
  package.json
  src/recorder/events/event.js
Labels: BLOCKER, Ready For Review, bug

#40 Trigger custom event on plugin event listener
  package.json
  src/index.js
  src/recorder/recorder.js
Labels: enhancement

#39 Record context and index of element for events
  package.json
  src/recorder/events/element-clicked.js
  src/recorder/events/element-dragged.js
  src/recorder/events/enter-key-pressed.js
  src/recorder/events/event-listener.js
  src/recorder/events/event.js
  src/recorder/events/handlers/click-event-handler.js
  src/recorder/events/handlers/drag-event-handler.js
  src/recorder/events/handlers/enter-event-handler.js
  src/recorder/events/handlers/input-event-handler.js
  src/recorder/events/value-entered.js
  src/recorder/helpers/html-tags.js
  src/recorder/helpers/rect-helper.js
Labels: feature

#41 Record events from iframes
  package.json
  src/recorder/events/event-listener.js
  src/recorder/events/handlers/click-event-handler.js
  src/recorder/events/handlers/drag-event-handler.js
  src/recorder/events/handlers/enter-event-handler.js
  src/recorder/events/handlers/input-event-handler.js
  src/recorder/events/handlers/navigate-event-handler.js
  src/recorder/recorder.js
Labels: feature
