Repository TestRigor/actions-recorder, pull requests merged in 2021-08, with the labels that each got.

#113 Restart recorder when any listener is removed
  package.json
  src/recorder/events/event-listener.js
  src/recorder/recorder.js
Labels: bug, Code Reviewed

#116 Update Circle CI AWS S3 Orb
  .circleci/config.yml
Labels: dependencies, BLOCKER, Code Reviewed

#120 Remove whitespace and asterisks before and after labels
  package-lock.json
  package.json
  src/recorder/events/event.js
Labels: enhancement, Code Reviewed
